name: Run ECS task
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_task:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-1"

      - name: Extract subnet_id
        id: extract_subnet_id
        run: echo "::set-output name=subnet_id::$(aws ec2 describe-subnets --query 'Subnets[0].SubnetId' --output text)"

      - name: Extract group_id
        id: extract_group_id
        run: echo "::set-output name=group_id::$(aws ec2 describe-security-groups --query 'SecurityGroups[0].GroupId' --output text)"

      - name: Run ECS task
        env:
          SUBNET_ID: ${{ steps.extract_subnet_id.outputs.subnet_id }}
          GROUP_ID: ${{ steps.extract_group_id.outputs.group_id }}
        run: aws ecs run-task --cluster k6TFCluster --task-definition k6TF --launch-type FARGATE --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID],securityGroups=[$GROUP_ID]},assignPublicIp=ENABLED}"
